print("")
print("")
print("")
print("K   K   AAAAA    III   TTTTT     OOO ")
print("K  K    A   A     I      T      O   O ")
print("K K     AAAAA     I      T      O   O ")
print("K  K    A   A     I      T      O   O ")
print("K   K   A   A    III     T       OOO ")
print("")
print("========================================")